name: On and Off the Wall
favicon: null
layout_spectrum: 0.8373742590192705
typography_spectrum: 0.437033737776801
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.027447456726804376
  lightness: 0.4471580113749951
  saturation: 0.6618212482426316
  rhythmicContrast: 0.5516344613861293
purpose: []
